sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: k5G5X3sR75yPsi9G4wYMOLPXv3W++SRRFKtdUr7iCWIVuoGwSRhSyAaKyuEJLo8/ynABPSJR37JqDb2jjKLLsVzmS1GIoHel3+e8+5l+5q3IiYPxYogieRfineiAjWbebeLtSb4A7RNzGVI47+jrG4pqVGgcXaL4C9lGVPIINfCP2bf9rw72Zk3pOSKwbxFISxM0BFA0uPH1+UXbv7E1Xdp4nTWQke6j/0BGWVFnDSeY/ZoM0uqqeBzDpPJ2/3KjLmnnbLCU/mghRCMjehAHdAkaXQ7Q47rD6q5EBxJhqjsx2pIYYOU8Bq+5PV6MkrX7nT5YeW50rfxIpJ0jEEv5mRau4Vni77/ikKkbDaS7L5iSahkmyRZyzmHX80vkpinVj7czSS7RXLue907k0ahMaUWp3SJiXXpYEs6n1o//h5PFJnw0GDGwYa9A413BugHdee2E3YyM4d9C8uIoAe6/nCmSJfVTqgGGNGIy6bEGkhkcUXh3RsD0MdUpx2oza7CzZcGNbhZbEeGwKbT0Anio5fV5hWBHR/QxS7AnQ2mrYe5FmM3NFRh7QJ7fqxmWeplwGryJJNYKNDG0SIA8eTtFAGvWDmrHdq0StEdmn48diuTvq4SrKSEoBULIjrqGivW02hiO5O0IR2nHQhvuWq0HLg9b7gAV+BelVKYCYkr5A4c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Darwinian-Hypothesis_2927
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy